# Generated by Django 2.0.2 on 2018-02-21 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=20)),
                ('password', models.BinaryField(max_length=64)),
                ('avatar', models.FilePathField()),
            ],
        ),
    ]
