# Generated by Django 2.0.2 on 2018-02-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20180221_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleUser',
            new_name='VUser',
        ),
    ]
