# Generated by Django 2.0.2 on 2018-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20180221_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuser',
            name='avatar',
            field=models.FilePathField(null=True),
        ),
    ]
