# Generated by Django 2.0.2 on 2018-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_vuser_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='intro.VUser'),
        ),
    ]
