# Generated by Django 2.0.2 on 2018-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_auto_20180223_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuser',
            name='ip',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vuser',
            name='port',
            field=models.IntegerField(default=-1),
        ),
    ]
