# Generated by Django 2.0.2 on 2018-03-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0009_auto_20180303_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuser',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='vuser',
            name='online',
        ),
        migrations.RemoveField(
            model_name='vuser',
            name='port',
        ),
    ]
