# Generated by Django 2.0.2 on 2018-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0011_auto_20180314_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuser',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='reqs', to='intro.VUser'),
        ),
    ]
