# Generated by Django 2.0.2 on 2018-04-19 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0012_vuser_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuser',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='vuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
