# Generated by Django 2.0.2 on 2018-04-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0013_auto_20180419_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuser',
            name='last_seen',
            field=models.BigIntegerField(default=0),
        ),
    ]
