# Generated by Django 2.0.2 on 2018-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0014_auto_20180419_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuser',
            name='salt',
            field=models.CharField(default='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', max_length=32),
        ),
    ]
