# Generated by Django 2.0.2 on 2018-10-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0015_vuser_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuser',
            name='password',
            field=models.BinaryField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vuser',
            name='salt',
            field=models.BinaryField(default='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', max_length=32),
        ),
    ]
